### ISSUE TITLE
How to make the inference for the ALDI-Best-ViT-Cityscapes

### ISSUE THREAD

**Issue by BalajiVenkatesan006** [justinkay/aldi#15]
So, I trained the models for both the backbones, one on this build_resnet_fpn_backbone and other on build_resnet_fpn_backbone. 

while inference I used the https://github.com/justinkay/aldi/blob/main/configs/detectron2/Base-RCNN-FPN.yaml
for the backbone resnet_fpn_backbone and t worked. 

Which config I should use for the backbone build_resnet_fpn_backbone. 

I tried to change the backbone in the config.  getting  this error: KeyError: "No object named 'build_vitdet_b_backbone' found in 'BACKBONE' registry!"

Below is my inference code:FYI

[check.txt](https://github.com/justinkay/aldi/files/15312509/check.txt)

**Comment by justinkay** [comment]
You should use the same config for inference as you do for training. And you need to make sure you import `aldi.backbone` in your script if you want to use `build_vitdet_b_backbone`, since you need to register the backbone with Detectron2 before using it. See: https://github.com/justinkay/aldi/blob/c2bf265199984a6f5de5003d36a59b6cce8619d9/tools/train_net.py#L19
